// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBI3Z_3ESazIqsnCxgaANRNvwbHSCXn8g',
    appId: '1:469991508388:web:7c2e7fe0114dc879641931',
    messagingSenderId: '469991508388',
    projectId: 'my-lifepilot',
    authDomain: 'my-lifepilot.firebaseapp.com',
    storageBucket: 'my-lifepilot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6WK7LDKb2pPAYDRKgumY8Ydht-DEuYQ8',
    appId: '1:469991508388:android:a8efb4d0dc0594f8641931',
    messagingSenderId: '469991508388',
    projectId: 'my-lifepilot',
    storageBucket: 'my-lifepilot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL9tuJjLNFqYGRLk9gQpdPVMTx1lhYLDo',
    appId: '1:469991508388:ios:ee869a1f58bd1445641931',
    messagingSenderId: '469991508388',
    projectId: 'my-lifepilot',
    storageBucket: 'my-lifepilot.firebasestorage.app',
    iosBundleId: 'com.example.lifepilotAi',
  );
}
